### ISSUE TITLE
More deteail of UFLD-SGPCS

### ISSUE THREAD

**Issue by O2andsAnoxia** [juliangebele/CARLANE#3]
Hi, thanks for the giant work. But whether there are a detail description of UFLD-SGPCS implement. Maybe it's a paper separate from “CARLANE: A Lane Detection Benchmark for Unsupervised Domain Adaptation from Simulation to multiple Real-World Domains”， bacause i don't seem to see the technical details in  the paper CARLANE Benchmark 

Looking forward to your reply !

**Comment by juliangebele** [comment]
Hi, thanks for your question! You can have a look at [Prototypical Cross-domain Self-supervised Learning for Few-shot Unsupervised Domain Adaptation](https://arxiv.org/abs/2103.16765) as well as [Self-training Guided Adversarial Domain Adaptation For Thermal Imagery](https://arxiv.org/abs/2106.07165) for more technical details about the algorithm. Due to limited paper space, we didn't go too deep explaining SGPCS...

**Comment by O2andsAnoxia** [comment]
ok, thanks!
