### ISSUE TITLE
Some questions about the implementation

### ISSUE THREAD

**Issue by zkyseu** [juliangebele/CARLANE#4]
Hi, thanks for your wonderful work. I have a simple question that has confused me for a long time. If the source domain only has two lanes but the target domain has four lanes. What is the number of lanes we should set for the model to implement classification? I mention you set 2 in your experiment. But this may cause the left 2 lanes can not to be trained. Could you help solve my confusion?

**Comment by juliangebele** [comment]
Hi, thanks for your question. 

Yes, I agree with you. If the number of output lanes is set to 2, the model will most likely focus on the ego lanes. The model will perform well, as long as the source and target distributions are well aligned. If you set the number of output lanes to 4, I guess, that this yields poor results on the outer lanes, since the pretrained feature encoder is heavily biased on the 2 ego lanes  (the labeled source domain is really dominant). Therefore it is hard for the model to adapt the "missing lanes" to the unlabeled target domain. If you really need to detect 4 lanes in the target domain, try generating a new source dataset with our dataset tools to fit your target domain distribution.

**Comment by zkyseu** [comment]
Thanks for your reply.

**Comment by zkyseu** [comment]
Could you provide the results of Source-only？I don not find it in your paper

**Comment by zkyseu** [comment]
> Could you provide the results of Source-only？I don not find it in your paper

Sorry, I have found this result in your paper
